### ISSUE TITLE
apkviewer TypeError exception on converting to hex

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#113]
```
What steps will reproduce the problem?
1. run apkviewer.py -i freedom-0.8.0.apk -o out

What is the expected output? What do you see instead?
got an exception:

<androguard.core.data.data.File instance at 0x7f519afbd050>
Traceback (most recent call last):
  File "./apkviewer.py", line 97, in <module>
    main(options, arguments)    
  File "./apkviewer.py", line 77, in main
    buff = dd.export_apk_to_gml()
  File "/dev/null/androguard/androguard/core/data/data.py", line 98, in export_apk_to_gml
    return self.apk_data.export_to_gml()
  File "/dev/null/androguard/androguard/core/data/data.py", line 378, in export_to_gml
    buff += "%s\n" % hex(node.file_crc)
TypeError: hex() argument can't be converted to hex

What version of the product are you using? On what operating system?
recent git version, linux 64bit, python 2.7



```

Original issue reported on code.google.com by `thuxn...@dexlabs.org` on 8 Mar 2013 at 9:15

Attachments:
- [freedom-0.8.0.apk](https://storage.googleapis.com/google-code-attachments/androguard/issue-113/comment-0/freedom-0.8.0.apk)

**Comment by GoogleCodeExporter** [comment]
```
Ok I will check that. BTW, DAD has a problem too during decompilation (with 
unresolved opcodes).
```

Original comment by `anthony....@gmail.com` on 8 Mar 2013 at 9:29
- Changed state: **Accepted**
