### ISSUE TITLE
TypeError: pretty_show() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#13]
```
Hi, I am trying to make androguard (latest version retrieved via hg) run on 
Ubuntu 11.10 (Python 2.7.2) but I get the following error:

ubuntu@ubuntu: ./androlyze.py -i my.apk -m . -p
Traceback (most recent call last):
  File "./androlyze.py", line 231, in <module>
    main(options, arguments)
  File "./androlyze.py", line 201, in main
    method.pretty_show( _a.get_analysis() )
TypeError: pretty_show() takes exactly 1 argument (2 given)
```

Original issue reported on code.google.com by `jan.stot...@googlemail.com` on 3 Feb 2012 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Can you test the latest commit on the mercurial repository ?
```

Original comment by `anthony....@gmail.com` on 3 Feb 2012 at 6:12
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
?
```

Original comment by `anthony....@gmail.com` on 6 Feb 2012 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Works now - thanks for fixing.
```

Original comment by `jan.stot...@googlemail.com` on 7 Feb 2012 at 6:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 10 Feb 2012 at 8:48
- Changed state: **Fixed**
