### ISSUE TITLE
"TypeError: exceptions must be old-style classes or derived from BaseException, not str " when running androdd.py 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#157]
```
What steps will reproduce the problem?
1../androdd.py -i **.apk -o */out -d -f PNG
2.
3.

What is the expected output? What do you see instead?
sx@sx-R408P:~/androguard$ ./androdd.py -i ~/crackme0502.apk -o ~/out/ -d -f png
Dump information /home/sx/crackme0502.apk in /home/sx/out/
Clean directory /home/sx/out/
Analysis ... End
Decompilation ...
Traceback (most recent call last):
  File "./androdd.py", line 222, in <module>
    main(options, arguments)
  File "./androdd.py", line 207, in main
    export_apps_to_format(options.input, a, options.output, options.limit, options.jar, options.decompiler, options.format)
  File "./androdd.py", line 127, in export_apps_to_format
    raise("invalid decompiler !")
TypeError: exceptions must be old-style classes or derived from BaseException, 
not str

What version of the product are you using? On what operating system?
Ubuntu 13.10 + Python 2.7.5 +  Revision: 1e64755cd512 

Please provide any additional information below.
I have the same problem with Issue 155. No reply untill now.
```

Original issue reported on code.google.com by `1101210...@pku.edu.cn` on 30 Apr 2014 at 3:53

**Comment by GoogleCodeExporter** [comment]
```
change raise 'String' with raise Exception('string')
```

Original comment by `amriabde...@gmail.com` on 16 Jul 2014 at 9:30
