### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_attributes'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#169]
```
What steps will reproduce the problem?
1. Install this app on device 
https://play.google.com/store/apps/details?id=com.symantec.mobilesecurity&hl=en_
GB
2. adb pull /data/app/com.symantec.mobilesecurity-1.apk
3. python mallodroid.py -f com.symantec.mobilesecurity-1.apk

What is the expected output? What do you see instead?
Package name: com.symantec.mobilesecurity
App requires INTERNET permission. Continue analysis...
Traceback (most recent call last):
  File "mallodroid.py", line 430, in <module>
    main()
  File "mallodroid.py", line 408, in main
    _gx = GVMAnalysis(_vmx, None)
  File "/auto/homes/lmrs2/chain_infiltration/wipe-apps/SSL/mallodroid-master/androguard/core/analysis/ganalysis.py", line 3252, in __init__
    n1.set_attributes( { "dynamic_code" : "true" } )
AttributeError: 'NoneType' object has no attribute 'set_attributes'



What version of the product are you using? On what operating system?
the latest version on 07 Oct 2014, from the repo.


Please provide any additional information below.


```

Original issue reported on code.google.com by `wasabe...@gmail.com` on 7 Oct 2014 at 7:46

Attachments:
- [com.symantec.mobilesecurity-1.apk](https://storage.googleapis.com/google-code-attachments/androguard/issue-169/comment-0/com.symantec.mobilesecurity-1.apk)

**Comment by GoogleCodeExporter** [comment]
```
Using:
Os: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-36-generic x86_64)
product version: Androlyze version 2.0


Additional info:


AttributeError                            Traceback (most recent call last)
/home/ubuntu/androguard/androlyze.py in <module>()
----> 1 a, d, dx = AnalyzeAPK('/home/ubuntu/NortonSecurityandAntivirus.apk')

/home/ubuntu/androguard/androlyze.py in AnalyzeAPK(filename, raw, decompiler)
    116     androconf.debug("APK ...")
    117     a = APK(filename, raw)
--> 118     d, dx = AnalyzeDex(a.get_dex(), raw=True, decompiler=decompiler)
    119     return a, d, dx
    120

/home/ubuntu/androguard/androlyze.py in AnalyzeDex(filename, raw, decompiler)
    146
    147     androconf.debug("GVMAnalysis ...")
--> 148     gx = GVMAnalysis(dx, None)
    149
    150     d.set_vmanalysis(dx)

/home/ubuntu/androguard/androguard/core/analysis/ganalysis.pyc in 
__init__(self, vmx, apk)
   3248                                                  "DEXCLASSLOADER" )
   3249
-> 3250                         n1.set_attributes( { "dynamic_code" : "true" } )
   3251                         n2.set_attributes( { "color" : DEXCLASSLOADER_COLOR } )
   3252                         self.G.add_edge( n2.id, n1.id )

AttributeError: 'NoneType' object has no attribute 'set_attributes'
```

Original comment by `for.teke...@gmail.com` on 15 Jan 2015 at 1:50
