### ISSUE TITLE
The problem of usage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#17]
```
Hi,

I have just begun to use androguard, but find a problem of usage. If I input a 

command like "./androlyze.py -i ~/Downloads/Mms.apk -m . -p" in the directory 

of androguard, it always gives a error warning like 
"Traceback (most recent call last):
  File "./androlyze.py", line 34, in <module>
    from decompiler import *
  File ".//decompiler/decompiler.py", line 23, in <module>
    from pygments.filter import Filter
ImportError: No module named pygments.filter".

But "./demos/dalvikvm_format_1.py" is ok. So I don't known the reason. I use 

androguard in the ARE Virtual Machine and always update androguard.

Really appreciate your help.

Thank you!

```

Original issue reported on code.google.com by `Sophie.x...@gmail.com` on 10 Feb 2012 at 8:41

**Comment by GoogleCodeExporter** [comment]
```
Hi,

for now, you need to install pygments (pygments.org).

We are working on a new ARE release :)

```

Original comment by `anthony....@gmail.com` on 10 Feb 2012 at 8:47
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
is it ok ?
```

Original comment by `anthony....@gmail.com` on 11 Feb 2012 at 9:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 17 Feb 2012 at 9:25
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I apologize for my delayed response. I have installed pygments and it works. 
But I 

cannot make a new ARE work, so I don't know the difference between the two 
versions.

And I am interested in your decompiler, dad. As you mentioned in  Black Hat 
2011,dad 

only uses Dalvik bytecode to create an original Java source code. Hence, I 
would 

like to know its effect. But when I use it, it always give me an error warning, 
like 

AttributeError                            Traceback (most recent call last)

/home/android/tools/androguard/androlyze.py in <module>()
----> 1 
      2 
      3 
      4 
      5 

AttributeError: 'DalvikVMFormat' object has no attribute 
'CLASS_Lcom_android_root_adbRoot'

And I start to use it with the command like 

android@honeynet:~/tools/androguard$ ./androlyze.py -s

In [1]: a, d, dx = AAnalyzeAPK("/home/android/Downloads/Mms.apk", 
decompiler="dad")

In [2]: d.CLASS_Lcom_android_root_adbRoot.METHOD_crypt.source()

Really sorry for my delayed response and thanks for your help!
```

Original comment by `Sophie.x...@gmail.com` on 19 Feb 2012 at 3:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 22 Feb 2012 at 5:06
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 27 Mar 2012 at 3:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 20 May 2012 at 9:19
- Changed state: **Fixed**
