### ISSUE TITLE
still have a problem with get_raw in dvm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#19]
```
What steps will reproduce the problem?
1.run dalvikvm_format_2.py with sample facebook apk file
2.get_raw() raised an exception 


What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "./demos/dalvikvm_format_2.py", line 46, in <module>
    fd.write( j.save() )
  File ".//core/bytecodes/dvm.py", line 3513, in save
    return self._get_raw()
  File ".//core/bytecodes/dvm.py", line 3541, in _get_raw
    l = self.map_list.get_raw()
  File ".//core/bytecodes/dvm.py", line 3449, in get_raw
    [ x.get_raw() for x in self.map_item ]
  File ".//core/bytecodes/dvm.py", line 3193, in get_raw
    return [ bytecode.Buff( self.__offset.off, self.format.get_value_buff() ) ] + [ i.get_raw() for i in self.item ]
  File ".//core/bytecodes/dvm.py", line 1369, in get_raw
    return [ bytecode.Buff(self.__offset.off, self.visibility.get_value_buff()) ] + self.annotation.get_raw()
  File ".//core/bytecodes/dvm.py", line 1338, in get_raw
    [ i.get_raw() for i in self.elements ]
  File ".//core/bytecodes/dvm.py", line 1310, in get_raw
    return [ bytecode.Buff(self.__offset.off, writeuleb128(self.name_idx) + self.value.get_raw()) ]
  File ".//core/bytecodes/dvm.py", line 1290, in get_raw
    return self.val.get_value_buff() + object_to_str( self.value )
TypeError: cannot concatenate 'str' and 'list' objects


What version of the product are you using? On what operating system?
Ubuntu 11.04

Please provide any additional information below.
I looked into the error, it seemed in EncodedValue, when type is 
EncodedAnnotation, get_raw() returned a list instead of string,therefore 
'return self.val.get_value_buff() + object_to_str( self.value )' threw 
TypeError exception. 

```

Original issue reported on code.google.com by `haoh...@gmail.com` on 20 Feb 2012 at 8:26

Attachments:
- [Facebook.apk](https://storage.googleapis.com/google-code-attachments/androguard/issue-19/comment-0/Facebook.apk)

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 22 Feb 2012 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
Do you use the mercurial version ?
```

Original comment by `anthony....@gmail.com` on 22 Feb 2012 at 5:08

**Comment by GoogleCodeExporter** [comment]
```
I checked out the code on Feb 3rd, is that mercurial version? I did not see any 
changes for get_raw() in dvm.py after Feb 3rd.
```

Original comment by `haoh...@gmail.com` on 22 Feb 2012 at 5:42

**Comment by GoogleCodeExporter** [comment]
```
ah ok sorry.

You would like to save an apk file ? 

If yes, this feature is not fully supported, you can only "read" a apk/dex 
file. If you would like to write, you can use smali/baksmali.
```

Original comment by `anthony....@gmail.com` on 23 Feb 2012 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your response. I indeed want to save an apk file. I am wondering 
when will you have this feature fully supported or could you please give me 
some hint to fix this problem I mentioned? Thanks again. Really appreciate it!
```

Original comment by `haoh...@gmail.com` on 23 Feb 2012 at 4:49

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 5 Aug 2012 at 10:54
- Changed state: **Fixed**
