### ISSUE TITLE
Androdd fails to produce png

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#2]
```
I try to generate a png for an APK:
$ ./androdd.py -i com.ppxiu.apk -o ppxiu.png -d -f png

The output is:
"getSmilType-BB@0x5e" [color="lightgray", label="5e new-instance v2 , [type@ 
344 Ljava/lang/StringBuilder;]\l62 const-string v3 , [string@ 261 '<img 
src="']\l66 invoke-direct v2 , v3 , [meth@ 2711 Ljava/lang/StringBuilder; 
(Ljava/lang/String;) V <init>]\l6c iget-object v3 , v4 , [field@ 105 
LDaemon/Service/MmsSender; Ljava/lang/String; Annex_name]\l70 invoke-virtual v2 
, v3 , [meth@ 2715 Ljava/lang/StringBuilder; (Ljava/lang/String;) 
Ljava/lang/StringBuilder; append]\l76 move-result-object v2\l78 const-string v3 
, [string@ 39 '" region="Image"/>']\l7c invoke-virtual v2 , v3 , [meth@ 2715 
Ljava/lang/StringBuilder; (Ljava/lang/String;) Ljava/lang/StringBuilder; 
append]\l82 move-result-object v2\l84 invoke-virtual v2 , [meth@ 2717 
Ljava/lang/StringBuilder; () Ljava/lang/String; toString]\l8a 
move-result-object v1\l"]
                      ^
Expected "}" (at char 2213), (line:20, col:23)
Traceback (most recent call last):
  File "./androdd.py", line 111, in <module>
    main(options, arguments)
  File "./androdd.py", line 97, in main
    export_apps_to_format( a, options.output, options.dot, options.format )
  File "./androdd.py", line 88, in export_apps_to_format
    method2format( filename + "." + _format, _format, raw = buff )
  File "/home/axelle/softs/androguard/core/bytecode.py", line 282, in method2format
    getattr(d, "write_" + _format)( output )
AttributeError: 'NoneType' object has no attribute 'write_png'


I use AndroGuard version from the repository (June 14th) on Debian.

```

Original issue reported on code.google.com by `aaforti...@gmail.com` on 14 Jun 2011 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
Hi,

fix in 
http://code.google.com/p/androguard/source/detail?r=26ecfb645135cc3be1c7006fadf5
ead3b8edb6ba

But it's possible to have "excepted" error from pydot, but the dot buffer is 
correct with dot program ...
```

Original comment by `anthony....@gmail.com` on 16 Jun 2011 at 8:26
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Yep. Now it works. I get plenty of messages, but in the end my PNGs
are generated.

Thanks !
```

Original comment by `aaforti...@gmail.com` on 16 Jun 2011 at 3:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 24 Oct 2011 at 1:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 3 Feb 2012 at 6:19
- Changed state: **Fixed**
