### ISSUE TITLE
Error in running androlyze.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#22]
```
Upon executing:

./androlyze.py -i /home/ubuntu/android.apk -m . -p

I got following error:

Traceback (most recent call last):
  File "./androlyze.py", line 42, in <module>
    from IPython.frontend.terminal.embed import InteractiveShellEmbed
ImportError: No module named IPython.frontend.terminal.embed


I am using ubuntu 10.04 64-bit and androguard 0.9

Any ideas to get through.

Thanks
-Sam


```

Original issue reported on code.google.com by `summaira...@gmail.com` on 13 Mar 2012 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
Hi,

in fact you need to update to the latest version of ipython, because some API 
are deprecated.

Otherwise, use the mercurial repository, the stable 1.0 version is not so far !
```

Original comment by `anthony....@gmail.com` on 13 Mar 2012 at 11:35
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
No luck... Now it prompts :

Traceback (most recent call last):
  File "./androlyze.py", line 42, in <module>
    from IPython.frontend.terminal.embed import InteractiveShellEmbed
ImportError: No module named terminal.embed


Thanks,
-Sam
```

Original comment by `summaira...@gmail.com` on 13 Mar 2012 at 11:51

**Comment by GoogleCodeExporter** [comment]
```
you have updated ipython ?
```

Original comment by `anthony....@gmail.com` on 13 Mar 2012 at 12:41

**Comment by GoogleCodeExporter** [comment]
```
yes I did... What else am I missing?
```

Original comment by `summaira...@gmail.com` on 14 Mar 2012 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
with the latest mercurial version of androguard ?
```

Original comment by `anthony....@gmail.com` on 14 Mar 2012 at 6:12

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I'm using androguard 1.0 rc1...
```

Original comment by `summaira...@gmail.com` on 15 Mar 2012 at 9:45

**Comment by GoogleCodeExporter** [comment]
```
Ok try with :
hg clone https://androguard.googlecode.com/hg/ androguard
```

Original comment by `anthony....@gmail.com` on 15 Mar 2012 at 10:35

**Comment by GoogleCodeExporter** [comment]
```
I downloaded... On running :

./androlyze.py -s

Prompts me an error:

Traceback (most recent call last):
  File "./androlyze.py", line 41, in <module>
    from IPython.frontend.terminal.embed import InteractiveShellEmbed
ImportError: No module named terminal.embed


Any solution why I'm not able to run it?


Thanks.
```

Original comment by `summaira...@gmail.com` on 15 Mar 2012 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
Have you removed the old ipython library ?
```

Original comment by `anthony....@gmail.com` on 21 Mar 2012 at 8:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 23 Mar 2012 at 12:59
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
solved thanks
```

Original comment by `CHMao2...@gmail.com` on 30 Mar 2012 at 10:46

**Comment by GoogleCodeExporter** [comment]
```
i got this problem when running androlyze

raceback (most recent call last):
  File "./androlyze.py", line 276, in <module>
    main(options, arguments)
  File "./androlyze.py", line 232, in main
    _a = AndroguardS( options.input )
  File "/home/notroot/androguard/androguard/core/androgen.py", line 239, in __init__
    self.__orig_a = Androguard( [ filename ], raw )
  File "/home/notroot/androguard/androguard/core/androgen.py", line 99, in __init__
    self._analyze()
  File "/home/notroot/androguard/androguard/core/androgen.py", line 113, in _analyze
    x = apk.APK( i )
  File "/home/notroot/androguard/androguard/core/bytecodes/apk.py", line 180, in __init__
    self.get_files_types()
  File "/home/notroot/androguard/androguard/core/bytecodes/apk.py", line 268, in get_files_types
    m = magic.Magic(magic_file=self.magic_file)
TypeError: __init__() got an unexpected keyword argument 'magic

can you help me to solve this problem ?

regards
Ammar
```

Original comment by `muhd.amm...@gmail.com` on 24 Jul 2012 at 5:55

**Comment by GoogleCodeExporter** [comment]
```
have you installed libmagic ?
```

Original comment by `anthony....@gmail.com` on 26 Jul 2012 at 8:32
