### ISSUE TITLE
XML xmlns

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#23]
```
backtrace: 

Traceback (most recent call last):
  File "./androlyze.py", line 243, in <module>
    main(options, arguments)
  File "./androlyze.py", line 197, in main
    _a = AndroguardS( options.input )
  File "/media/truecrypt1/androguard/androguard/core/androgen.py", line 238, in __init__
    self.__orig_a = Androguard( [ filename ], raw )
  File "/media/truecrypt1/androguard/androguard/core/androgen.py", line 91, in __init__
    self._analyze()
  File "/media/truecrypt1/androguard/androguard/core/androgen.py", line 112, in _analyze
    x = apk.APK( i )
  File "/media/truecrypt1/androguard/androguard/core/bytecodes/apk.py", line 108, in __init__
    self.xml[i] = minidom.parseString( AXMLPrinter( self.zip.read( i ) ).getBuff() )
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1924, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: unbound prefix: line 9, column 0


support multiple xmlns
```

Original issue reported on code.google.com by `anthony....@gmail.com` on 20 Mar 2012 at 11:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 11 Apr 2012 at 3:25
- Changed state: **Fixed**
