### ISSUE TITLE
ImportError: No module named libelsign

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#26]
```
Upon executing:
android@honeynet:~/androguard$ ./androsign.py -h

I got following error:
Traceback (most recent call last):
  File "./androsign.py", line 29, in <module>
    from elsim.elsign import dalvik_elsign
  File "./elsim/elsim/elsign/dalvik_elsign.py", line 29, in <module>
    from libelsign.libelsign import Elsign, entropy
ImportError: No module named libelsign

I am using ARE(Android Reverse Engineering) Virtual Machine

>Any ideas to get through.
thank you.

```

Original issue reported on code.google.com by `tse...@gmail.com` on 27 Mar 2012 at 10:20

**Comment by GoogleCodeExporter** [comment]
```
please compile all sources in the main directory:

"make"
```

Original comment by `anthony....@gmail.com` on 27 Mar 2012 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
I have tried to compile,and the prompt reply:

  CCP dvm.o
In file included from dvm.cc:21:
dvm.h:23:20: error: Python.h: No such file or directory
In file included from /usr/include/c++/4.4/ext/hash_map:60,
                 from dvm.h:32,
                 from dvm.cc:21:
/usr/include/c++/4.4/backward/backward_warning.h:28:2: warning: #warning This 
file includes at least one deprecated or antiquated header which may be removed 
without further notice at a future date. Please use a non-deprecated interface 
with equivalent functionality instead. For a listing of replacement headers and 
interfaces, consult the file backward_warning.h. To disable this warning use 
-Wno-deprecated.
In file included from dvm.cc:21:
dvm.h:167: error: ISO C++ forbids declaration of ‘PyObject_HEAD’ with no 
type
dvm.h:169: error: ISO C++ forbids declaration of ‘PyObject’ with no type
dvm.h:169: error: expected ‘;’ before ‘*’ token
               .
               .
               . 


still "android@honeynet:~/androguard$ ./androsign.py -h" command doesn't work.

```

Original comment by `tse...@gmail.com` on 27 Mar 2012 at 11:42

**Comment by GoogleCodeExporter** [comment]
```
dvm.h:23:20: error: Python.h: No such file or directory

install python2.7-dev
```

Original comment by `anthony....@gmail.com` on 27 Mar 2012 at 11:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 27 Mar 2012 at 3:16
- Changed state: **Invalid**
