### ISSUE TITLE
 diff module was not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#31]
```
What steps will reproduce the problem?
1. import androlyze.py 
2. run the python programm

What is the expected output? What do you see instead?
the programm should just run, instead an error is thrown

What version of the product are you using? On what operating system?
ubuntu 11.04, newest hg checkout


Please provide any additional information below.

Traceback (most recent call last):
  File "myscript.py", line 6, in <module>
    from androlyze import AAnalyzeAPK
  File "/foo/bar/bla/androguard/androlyze.py", line 36, in <module>
    from androguard.core.analysis.diff import *
ImportError: No module named diff

ll androguard/androguard/core/analysis
ls: unrecognized prefix: hl
ls: unparsable value for LS_COLORS environment variable
total 308
-rw-rw-r-- 1 android android 78620 2012-04-02 12:05 analysis.py
-rw-rw-r-- 1 android android 84849 2012-04-02 12:08 analysis.pyc
-rw-rw-r-- 1 android android 20678 2012-04-02 12:05 ganalysis.py
-rw-rw-r-- 1 android android 14943 2012-04-02 12:08 ganalysis.pyc
-rw-rw-r-- 1 android android     0 2012-04-02 12:05 __init__.py
-rw-rw-r-- 1 android android   136 2012-04-02 12:08 __init__.pyc
-rw-rw-r-- 1 android android 44477 2012-04-02 12:05 risk.py
-rw-rw-r-- 1 android android 27319 2012-04-02 12:08 risk.pyc
-rw-rw-r-- 1 android android 12837 2012-04-02 12:05 sign.py
-rw-rw-r-- 1 android android 10625 2012-04-02 12:08 sign.pyc



```

Original issue reported on code.google.com by `5hp...@gmail.com` on 2 Apr 2012 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
ok found out that my androlyze script was some kind of old... now i got another 
error:
Traceback (most recent call last):
  File "myscript.py", line 6, in <module>
    from androlyze import AAnalyzeAPK
  File "./androguard/androlyze.py", line 41, in <module>
    from IPython.frontend.terminal.embed import InteractiveShellEmbed
ImportError: No module named terminal.embed

but ipython is installed 
```

Original comment by `5hp...@gmail.com` on 2 Apr 2012 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
For the first issue, I'm writing a doc for that.

For the second issue, you must install the latest version of ipython
```

Original comment by `anthony....@gmail.com` on 2 Apr 2012 at 10:30
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 17 Jul 2012 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
All this part is now in Elsim !
```

Original comment by `anthony....@gmail.com` on 5 Aug 2012 at 10:54
- Changed state: **Fixed**
