### ISSUE TITLE
No "elsim" folder in the root androguard Directory 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#33]
```
What steps will reproduce the problem?
1. python ./androsign.py -h


What is the expected output? What do you see instead?
Help Discription

What version of the product are you using? On what operating system?
1.0 on ubuntu

Please provide any additional information below.
when runnind androsign.py, it says 

Traceback (most recent call last):
  File "androsign.py", line 29, in <module>
    from elsim.elsign import dalvik_elsign
  File "./elsim/elsim/elsign/dalvik_elsign.py", line 29, in <module>
    from libelsign.libelsign import Elsign, entropy
ImportError: No module named libelsign

===> and i have checked your hg url, there is no elsim directory. THANK YOU.
```

Original issue reported on code.google.com by `tobesufe...@gmail.com` on 6 Apr 2012 at 9:11

**Comment by GoogleCodeExporter** [comment]
```
update your mercurial repository please
```

Original comment by `anthony....@gmail.com` on 15 Apr 2012 at 9:54
- Changed state: **Invalid**
