### ISSUE TITLE
apkviewer.py - KeyError: 'META-INF/MANIFEST.MF'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#41]
```
This error spawns while parsing the Manifest.xml file.

android@honeynet:~/tools/androguard$ python apkviewer.py -i 
/home/android/PFE/APKS/Brighteriffic_1.0.3.apk -o 
/home/android/PFE/APKS/Brighter
Traceback (most recent call last):
  File "apkviewer.py", line 97, in <module>
    main(options, arguments)    
  File "apkviewer.py", line 75, in main
    dd = data.Data(vm, vmx, gvmx, a)
  File "/home/android/tools/androguard/androguard/core/data/data.py", line 80, in __init__
    self.apk_data = ApkViewer( self.a )
  File "/home/android/tools/androguard/androguard/core/data/data.py", line 325, in __init__
    for x, y, z in self.a.get_files_information() :
  File "/home/android/tools/androguard/androguard/core/bytecodes/apk.py", line 224, in get_files_information
    yield i, self.files[ i ], self.files_crc32[ i ]
KeyError: 'META-INF/MANIFEST.MF'
```

Original issue reported on code.google.com by `thomas.d...@gmail.com` on 7 May 2012 at 4:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 7 May 2012 at 6:37
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I encounter the same problem.
```

Original comment by `aaforti...@gmail.com` on 30 May 2012 at 3:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 22 Jun 2012 at 7:38
- Changed state: **Fixed**
