### ISSUE TITLE
Androrisk: TaintedPackage instance has no attribute 'get_info'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#55]
```
What steps will reproduce the problem?
1. use androrisk on different dex files:
./androrisk.py -a -i somedex.dex
./androrisk.py -m -i another.dex

What is the expected output? What do you see instead?
got the following error message:
Traceback (most recent call last):
  File "./androrisk.py", line 88, in <module>
    main(options, arguments)
  File "./androrisk.py", line 52, in main
    analyze_dex( options.input, ri, open(options.input, "r").read(), options.analysis, options.method )
  File "./androrisk.py", line 41, in analyze_dex
    print filename, ri.with_dex( d, analysis_method=method )
  File "/home/android/git/androguard/androguard/core/analysis/risk.py", line 792, in with_dex
    return self.with_dex_direct( vm, vmx, apk, analysis_method )
  File "/home/android/git/androguard/androguard/core/analysis/risk.py", line 812, in with_dex_direct
    self.__eval_risk_dyn( vmx, risks )
  File "/home/android/git/androguard/androguard/core/analysis/risk.py", line 686, in __eval_risk_dyn
    if m.get_info() == "Ldalvik/system/DexClassLoader;" :
AttributeError: TaintedPackage instance has no attribute 'get_info'



What version of the product are you using? On what operating system?
./androrisk.py -v
Androrisk version 1.5

and also the latest hg version of androguard
```

Original issue reported on code.google.com by `5hp...@gmail.com` on 27 Jun 2012 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Please use this version :
http://code.google.com/p/androguard/source/detail?r=1a43fd59b3bd624767174b3b734b
4bfa18294d13

I modified a lot of things to the current version
```

Original comment by `anthony....@gmail.com` on 27 Jun 2012 at 10:54
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
okay, it works for the moment!
```

Original comment by `5hp...@gmail.com` on 27 Jun 2012 at 10:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 5 Aug 2012 at 10:54
- Changed state: **Fixed**
