### ISSUE TITLE
Can't produce gexf file on ubuntu 10.04 even when requirements are fulfilled.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#6]
```
/androguard-0.9$ ./androgexf.py -i 
'/home/suresh/Bureaublad/AndroidCracking/vddebug.apk' -o ./xxxxx.gexf
/usr/lib/pymodules/python2.6/matplotlib/numerix/__init__.py:18: 
DeprecationWarning: 
**********************************************************
matplotlib.numerix and all its subpackages are deprecated.
They will be removed soon.  Please use numpy instead.
**********************************************************

  warnings.warn(msg, DeprecationWarning)
/usr/lib/pymodules/python2.6/networkx/generators/hybrid.py:16: 
DeprecationWarning: the sets module is deprecated
  import sets
Traceback (most recent call last):
  File "./androgexf.py", line 28, in <module>
    import androguard, apk, dvm, analysis, ganalysis, androconf 
  File ".//core/analysis/ganalysis.py", line 23, in <module>
    import libsign
ImportError: liblzma.so.5: cannot open shared object file: No such file or 
directory

```

Original issue reported on code.google.com by `xur...@gmail.com` on 28 Oct 2011 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
Ok, I remove libsign from ganalysis.py because it's not necessary.

Update your repository.

Thx
```

Original comment by `anthony....@gmail.com` on 28 Oct 2011 at 6:27
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
The same problem also occurs, when executing the sample command line using 
androlyze.py
```

Original comment by `jan.stot...@googlemail.com` on 3 Feb 2012 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
Can you paste the error ?
```

Original comment by `anthony....@gmail.com` on 3 Feb 2012 at 6:11
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Ok you need to install compression requirements
```

Original comment by `anthony....@gmail.com` on 6 Feb 2012 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Yes, works after installing libzip-dev libbz2-dev and liblzma-dev. Make process 
also works now.
```

Original comment by `jan.stot...@googlemail.com` on 6 Feb 2012 at 6:08

**Comment by GoogleCodeExporter** [comment]
```
ok !
```

Original comment by `anthony....@gmail.com` on 6 Feb 2012 at 6:10
- Changed state: **Fixed**
