### ISSUE TITLE
apkviewer error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#61]
```
What steps will reproduce the problem?
1. follow the installation guide
2.run the command
./apkviewer.py -i apks/sbi.apk -o apks/

What is the expected output? What do you see instead?
expected : apkviewer output
got      : File 
"/home/abhi/Downloads/libraries/androguard/androguard/core/bytecodes/apk.py", 
line 266, in get_files_types
    m = magic.Magic()
TypeError: __init__() takes exactly 2 arguments (1 given)

What version of the product are you using? On what operating system?
latest hg pull as on 16th july

Please provide any additional information below.

root@eon:/home/abhi/Downloads/libraries/androguard# ./apkviewer.py -i 
apks/sbi.apk -o apks/
Traceback (most recent call last):
  File "./apkviewer.py", line 97, in <module>
    main(options, arguments)    
  File "./apkviewer.py", line 75, in main
    dd = data.Data(vm, vmx, gvmx, a)
  File "/home/abhi/Downloads/libraries/androguard/androguard/core/data/data.py", line 80, in __init__
    self.apk_data = ApkViewer( self.a )
  File "/home/abhi/Downloads/libraries/androguard/androguard/core/data/data.py", line 325, in __init__
    for x, y, z in self.a.get_files_information() :
  File "/home/abhi/Downloads/libraries/androguard/androguard/core/bytecodes/apk.py", line 298, in get_files_information
    self.get_files_types()
  File "/home/abhi/Downloads/libraries/androguard/androguard/core/bytecodes/apk.py", line 266, in get_files_types
    m = magic.Magic()
TypeError: __init__() takes exactly 2 arguments (1 given)
```

Original issue reported on code.google.com by `abhinav....@mad-screens.com` on 16 Jul 2012 at 8:15

**Comment by GoogleCodeExporter** [comment]
```
Have you follow the requirements ? 

http://code.google.com/p/androguard/wiki/Installation
```

Original comment by `anthony....@gmail.com` on 17 Jul 2012 at 7:30
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
libmagic bug
```

Original comment by `anthony....@gmail.com` on 26 Sep 2012 at 6:22
- Changed state: **Invalid**
