### ISSUE TITLE
Unable to create gexf file on ubuntu 10.04 with full requirements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#7]
```
..../androguard-0.9$ ./androgexf.py -i '.../xxx.apk' -o ./xxx.gexf
/usr/lib/pymodules/python2.6/matplotlib/numerix/__init__.py:18: 
DeprecationWarning: 
**********************************************************
matplotlib.numerix and all its subpackages are deprecated.
They will be removed soon.  Please use numpy instead.
**********************************************************

  warnings.warn(msg, DeprecationWarning)
/usr/lib/pymodules/python2.6/networkx/generators/hybrid.py:16: 
DeprecationWarning: the sets module is deprecated
  import sets
Traceback (most recent call last):
  File "./androgexf.py", line 71, in <module>
    main(options, arguments)    
  File "./androgexf.py", line 57, in main
    gvmx = ganalysis.GVMAnalysis( vmx, a )
  File ".//core/analysis/ganalysis.py", line 69, in __init__
    self.vm = self.vmx.get_vm()
AttributeError: VMAnalysis instance has no attribute 'get_vm'

```

Original issue reported on code.google.com by `xur...@gmail.com` on 28 Oct 2011 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
Are you sure to be at the latest version ? 

Because get_vm is present in VMAnalysis : 
http://code.google.com/p/androguard/source/browse/core/analysis/analysis.py
```

Original comment by `anthony....@gmail.com` on 28 Oct 2011 at 7:02
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Now that I am using newest version, I am getting this error:

abce@abcd-laptop:~/abcd/abcd/androguard$ ./androgexf.py -i 
'/abcd/abcd/abcd/abcd/abcd.apk' -o ./abcd.gexf
/usr/lib/pymodules/python2.6/matplotlib/numerix/__init__.py:18: 
DeprecationWarning: 
**********************************************************
matplotlib.numerix and all its subpackages are deprecated.
They will be removed soon.  Please use numpy instead.
**********************************************************

  warnings.warn(msg, DeprecationWarning)
/usr/lib/pymodules/python2.6/networkx/generators/hybrid.py:16: 
DeprecationWarning: the sets module is deprecated
  import sets
Traceback (most recent call last):
  File "./androgexf.py", line 68, in <module>
    main(options, arguments)    
  File "./androgexf.py", line 56, in main
    gvmx.export_to_gexf( options.output )
  File ".//core/analysis/ganalysis.py", line 247, in export_to_gexf
    for node in self.G.node :
AttributeError: 'DiGraph' object has no attribute 'node'

```

Original comment by `xur...@gmail.com` on 29 Oct 2011 at 1:04

**Comment by GoogleCodeExporter** [comment]
```
Ok maybe I'm using a too recent version of networkx. I updated the repository 
by using the specific methods to get nodes and edges.

Tell me if it's ok.
```

Original comment by `anthony....@gmail.com` on 29 Oct 2011 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot. Its creating gexf file perfectly now.
```

Original comment by `xur...@gmail.com` on 29 Oct 2011 at 9:19

**Comment by GoogleCodeExporter** [comment]
```
Ok cool :)
```

Original comment by `anthony....@gmail.com` on 29 Oct 2011 at 9:20
- Changed state: **Fixed**
