### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#79]
```
I've installed all required apps. Then I've try to open it:
   python startQT.py
It hasn't open and wrote this:
   Traceback (most recent call last):
  File "startQT.py", line 18, in <module>
    from GetMethods import *
  File "/home/danpetruk/3/GetMethods.py", line 20, in <module>
    import androguard, analysis, androlyze
  File "/home/danpetruk/3/androguard/androlyze.py", line 35, in <module>
    import IPython.ipapi
  ImportError: No module named ipapi

---
p.s. os - linux mint

```

Original issue reported on code.google.com by `danpet...@gmail.com` on 18 Oct 2012 at 3:32

**Comment by GoogleCodeExporter** [comment]
```
please install latest version of ipython
```

Original comment by `anthony....@gmail.com` on 18 Oct 2012 at 3:34
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Issue 80 has been merged into this issue.
```

Original comment by `anthony....@gmail.com` on 18 Oct 2012 at 3:34
