### ISSUE TITLE
androguard fails to load jar files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#8]
```
What steps will reproduce the problem?
a = androguard.AndroGuardS("attached jar file")
a.show
What is the expected output? What do you see instead?
should print information about the jar file, instead it dies accessing outside 
of a list - this actually helps with all jar files (classes) that I tried to 
load, except very simple ones.

Traceback (most recent call last):
  File "./bla.py", line 13, in <module>
    a = androguard.AndroguardS(sys.argv[1])
  File "/home/spjsschl/androguard/androguard.py", line 448, in __init__
    self.__orig_a = Androguard( [ filename ], raw )
  File "/home/spjsschl/androguard/androguard.py", line 240, in __init__
    self._analyze()
  File "/home/spjsschl/androguard/androguard.py", line 275, in _analyze
    self.__bc.append( (j[0], BC( jvm.JVMFormat(j[1]) ) ) )
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 2893, in __init__
    self._load_class()
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 2964, in _load_class
    mi = MethodInfo( self.__CM, self )
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 789, in __init__
    ai = AttributeInfo( self.__CM, buff )
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 2527, in __init__
    self._info = ATTRIBUTE_INFO_DESCR[ self.__name ](self.__CM, buff)
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 1545, in __init__
    self.__code = JavaCode( class_manager, buff.read( self.low_struct.get_value().code_length ) )
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 1202, in __init__
    r_function, v_function, r_buff, r_format, f_function = EXTRACT_INFORMATION_SIMPLE( op_value )
  File "/home/spjsschl/androguard//core/bytecodes/jvm.py", line 427, in EXTRACT_INFORMATION_SIMPLE
    r_function = JAVA_OPCODES[ op_value ][2]
IndexError: list index out of range

What version of the product are you using? On what operating system?
I am using the current mercurial version on ubuntu oneiric.


```

Original issue reported on code.google.com by `spjss...@gmail.com` on 22 Nov 2011 at 12:40

Attachments:
- [field.jar](https://storage.googleapis.com/google-code-attachments/androguard/issue-8/comment-0/field.jar)

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 22 Nov 2011 at 10:27
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 26 Nov 2011 at 8:18
- Changed state: **Fixed**
