### ISSUE TITLE
Sublime Text 2 Plugin : Can not open APK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [karlredgate/androguard#99]
```
What steps will reproduce the problem?
1.use Ctrl+F5 to open an APK
2.in console of Sublime Text 2,we'll see:
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./ag.py", line 614, in run
AttributeError: 'NoneType' object has no attribute 'file_name'


What version of the product are you using? On what operating system?
ag-st-1.9
os:ubuntu 12.04


```

Original issue reported on code.google.com by `liuxiaow...@gmail.com` on 4 Jan 2013 at 3:39

**Comment by GoogleCodeExporter** [comment]
```
OH,I found what's my mistake
before use Ctrl+f5,We must open the APK with sublime first.
```

Original comment by `liuxiaow...@gmail.com` on 4 Jan 2013 at 3:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `anthony....@gmail.com` on 4 Jan 2013 at 4:22
- Changed state: **Invalid**
